### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by sandeshpaudyal** [mailgun/mailgun-php#646]
Fatal error: Uncaught TypeError: Argument 1 passed to Mailgun\Mailgun::__construct() must be an instance of Mailgun\HttpClient\HttpClientConfigurator, string given, called in C:\xampp\htdocs\mailgun\mailgun-php\sendemail.php on line 7 and defined in C:\xampp\htdocs\mailgun\mailgun-php\src\Mailgun.php:55 Stack trace: #0 C:\xampp\htdocs\mailgun\mailgun-php\sendemail.php(7): Mailgun\Mailgun->__construct('262d28e84766e72...') #1 {main} thrown in C:\xampp\htdocs\mailgun\mailgun-php\src\Mailgun.php on line 55

**Comment by DavidGarciaCat** [comment]
Hi, @sandeshpaudyal 

Can you please elaborate a bit more?
- How did you install the package?
- How did you instantiate the client?
- What is the whole flow of your error?

Cheers,

**Comment by sandeshpaudyal** [comment]
@DavidGarciaCat 
**1. It was installed using composer via the code below.**
# Install Composer
curl -sS https://getcomposer.org/installer | php
# Add Mailgun and Guzzle6 as a dependency (see GitHub README below for more info)
php composer.phar require mailgun/mailgun-php php-http/guzzle6-adapter php-http/message

2.  **Instantiation**
require 'vendor/autoload.php';
use Mailgun\Mailgun;
$mg = Mailgun::create('YOUR_API_KEY');
$mg->messages()->send('YOUR_DOMAIN_NAME', [
  'from'    => 'Excited User <mailgun@YOUR_DOMAIN_NAME>',
  'to'      => 'Baz <YOU@YOUR_DOMAIN_NAME>',
  'subject' => 'Hello',
  'text'    => 'Testing some Mailgun awesomness!'
]);

3. Error was shown when trying to send the email.

**Comment by sandeshpaudyal** [comment]
@DavidGarciaCat 
**1. It was installed using composer via the code below.**

- Installing Composer

- [ ] curl -sS https://getcomposer.org/installer | php

- Adding Mailgun and Guzzle6 as a dependency

- [ ] php composer.phar require mailgun/mailgun-php php-http/guzzle6-adapter php-http/message

- [ ] Than updating the composer.

2.  **Instantiation**

require 'vendor/autoload.php';
use Mailgun\Mailgun;

$mgClient = new Mailgun('<api key>');
$domain = "--verified domain name-->";

$result = $mgClient->sendMessage($domain, array(
    'from'  => 'email@gmail.com',
    'to'    => 'email@gmail.com',
    'subject' => 'Hello',
    'text'  => 'Testing some Mailgun awesomness!'
));



3. Error was shown when trying to send the email.

**Comment by dadeg** [comment]
I got this same error, using the same code. The readme for this package actually includes a different example  (https://github.com/mailgun/mailgun-php#usage) which also gives a fatal error (a different one)

**Comment by joshwenke** [comment]
I am having this same issue. Installed Mailgun via composer on my Mac, then transferred the files to a DreamHost server. I've seen two ways to send email. Here's an alternative option I found that still didn't work, and gave me this error:
`require 'includes/lib/vendor/autoload.php';

$client = new \Http\Adapter\Guzzle6\Client();

# First, instantiate the SDK with your API credentials
$mg = new \Mailgun\Mailgun('x', $client);

# Make the call to the client.
$mg->sendMessage('mydomain.com', array(
    'from'    => 'hello@mydomain.com',
    'to'      => 'hello@ mydomain.com',
    'subject' => 'Hello',
    'text'    => 'Testing some Mailgun awesomness!'));
`

**Comment by Clinton594** [comment]
Fatal error: Uncaught TypeError: Argument 1 passed to Mailgun\Mailgun::__construct() must be an instance of Mailgun\HttpClient\HttpClientConfigurator, string given, called in C:\wamp64\www\mylelojobs\admin\cron_mailer_test.php on line 17 and defined in C:\wamp64\www\mylelojobs\admin\vendor\mailgun\mailgun-php\src\Mailgun.php on line 55

Above is my error.
But this is my code below

$mgClient = new Mailgun($apiKey);
$result = $mgClient->sendMessage($domain, array(
	'from'	=> 'Mylelo Jobs <info@mylelojobs.com>',
	'to'	=> 'Clinton <ucmodulus@gmail.com>',
	'subject' => 'Hello',
	'text'	=> 'Testing some Mailgun awesomness!'
));

**Comment by 50shashwat** [comment]
I got the same error
 `[500]: / - Uncaught TypeError: Argument 1 passed to Mailgun\Mailgun::__construct() must be an instance of Mailgun\HttpClient\HttpClientConfigurator, string given,`

**Comment by mitkodelibaltov** [comment]
Hi, I have the same issue.

I am using PHP Api v2 (as the server doesn't support PHP7). 

When I tried to use my domain (EU) it throws this error mentioned above.

Message: Argument 2 passed to Mailgun\Mailgun::__construct() must be an instance of Http\Client\HttpClient, string given

Message: Argument 3 passed to Mailgun\Connection\RestClient::__construct() must be an instance of Http\Client\HttpClient, string given


Tried to send , 'https://api.eu.mailgun.net' as 2nd parameter on Mailgun. My domain is set and approved. Had no issues sending with test domain (US server).


If I try without the 2nd parameter (eu server) I get the following error:

Fatal error: Uncaught exception 'Mailgun\Connection\Exceptions\MissingEndpoint' with message 'The endpoint you've tried to access does not exist. Check if the domain matches the domain you have configure on Mailgun. Domain not found

The Domain is all set and verified.

**Comment by nicdnepr** [comment]
is any news?

**Comment by 50shashwat** [comment]
I have fixed this issue using 

`
$mg = Mailgun::create('key'); // For US servers

$domain = "mail.abc.com";  //this was the error, i have been using https://v2.mailgun...../mail.abc.com
$mg->messages()->send($domain , [
  'from'    => 'bob@example.com',
  'to'      => 'sally@example.com',
  'subject' => 'The PHP SDK is awesome!',
  'text'    => 'It is so simple to send a message.'
]);
`

**Comment by placeposition** [comment]
Is there a breaking change to the latest SDK? Previously working methods with sendMessage() the way other comments have it no longer work. The 'fix' isn't a fix- it works but refused many parameters and doesn't address the real issue that a previously working function which is still in current documentation gives an error.

**Comment by placeposition** [comment]
$mg->messages()->send() gives me this error when I try to include v:my-var 

```

First argument to "Http\Message\MultipartStream\MultipartStreamBuilder::createStream()" must be a string, resource or StreamInterface

```

```

$config = [
								'from'    	=> 	stripslashes($e->outbox_from_name).' <'.$e->outbox_from.'>',
								'to'      	=> 	$e->outbox_to,
								'subject' 	=> 	stripslashes($e->outbox_subject),
								'html'    	=> 	$markup,
								'o:tracking-clicks' => $track_clicks,
								'o:tracking-opens' => $track_opens,
								'v:custId' => $e->cust_id, // <- this kills it
								//'v:outboxId' => $e->outbox_id,
								//'v:domain' => $e->outbox_domain
							];

```

**Comment by trondhuso** [comment]
@sandeshpaudyal, @dadeg , @joshwenke 

The reason is that you are using the old api. 

to initialise the client you do:
$mgClient = Mailgun::create('key-example');

Then the rest is almost equal, except when you want to send the message:
$mgClient->messages()->send($domain, array('to'=> ....);

**Comment by 1stevengrant** [comment]
> @sandeshpaudyal, @dadeg , @joshwenke
> 
> The reason is that you are using the old api.
> 
> to initialise the client you do:
> $mgClient = Mailgun::create('key-example');
> 
> Then the rest is almost equal, except when you want to send the message:
> $mgClient->messages()->send($domain, array('to'=> ....);

perhaps would be useful in this instance if the docs reflected the package?

**Comment by matthew-b-shaw** [comment]
Is the documentation provided by MailGun itself using two options for sending? Looking at these docs for PHP:

- https://documentation.mailgun.com/en/latest/user_manual.html#sending-via-api
- https://documentation.mailgun.com/en/latest/api-sending.html#examples

I see both options used:

```
$mg = Mailgun::create('YOUR_API_KEY');
$mg->messages()->send('YOUR_DOMAIN_NAME', [...]);
```

```
$mgClient = new Mailgun('YOUR_API_KEY');
$domain = "YOUR_DOMAIN_NAME";
$result = $mgClient->sendMessage($domain, array(...);
```

**Comment by 1stevengrant** [comment]
I wasn't looking at sending an email, rather subscribing an email address to a mailing list.

The docs say

```
# Instantiate the client.
$mgClient = new Mailgun('YOUR_API_KEY');
$listAddress = 'LIST@YOUR_DOMAIN_NAME';

# Issue the call to the client.
$result = $mgClient->post("lists/$listAddress/members", array(
    'address'     => 'bar@example.com',
    'name'        => 'Bob Bar',
    'description' => 'Developer',
    'subscribed'  => true,
    'vars'        => '{"age": 26}'
));
```

but the `post` method on `$mgClient` doesn't exist. Same issue in #659

**Comment by code2exe** [comment]
The Mailgun api docs isn't clear enough; every thing I tried just doesn't work.

**Comment by Maerryham** [comment]
please any solutions yet, i am also having the same issue 
`Argument 1 passed to Mailgun\Mailgun::__construct() must be an instance of
		Mailgun\HttpClient\HttpClientConfigurator, string given, called in
		C:\Users\lawal\mydiamondadmin\rest-api\App\Controllers\ApiController.php on line 34`

**Comment by Maerryham** [comment]
i changed the syntax to the documentation syntax

$mgClient = Mailgun::create('PRIVATE_API_KEY', 'https://API_HOSTNAME');
$domain = "YOUR_DOMAIN_NAME";
$params = array(
  'from'    => 'Excited User <YOU@YOUR_DOMAIN_NAME>',
  'to'      => 'bob@example.com',
  'subject' => 'Hello',
  'text'    => 'Testing some Mailgun awesomness!'
);

# Make the call to the client.
$mg->messages()->send($domain, $params);

Then i got 
`No PSR-17 url factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation`

After then i installed 
`composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7`

And then i got

`Mailgun's servers are currently unreachable.`

Can someone help on this

**Comment by Maerryham** [comment]
I have gotten a solution
i did
 `php composer.phar require mailgun/mailgun-php php-http/guzzle6-adapter php-http/message
`
`$mgClient = Mailgun::create('PRIVATE_API_KEY');
$domain = "YOUR_DOMAIN_NAME";
$params = array(
'from' => 'Excited User <YOU@YOUR_DOMAIN_NAME>',
'to' => 'bob@example.com',
'subject' => 'Hello',
'text' => 'Testing some Mailgun awesomness!'
);

$mgClient->messages()->send($domain, $params);`

**Comment by purpletoolz** [comment]
Didn't work for me.  I got:
Exception has occurred.
Http\Discovery\Exception\PuliUnavailableException: Puli Factory is not available
(line 40 PuliBetaStrategy.php)

When executing:
$mg = Mailgun::create($GLOBALS['MAILGUN_PRI_API_KEY']);

Stragely, this whole problem has only just started?? I've been using this code for months without a problem.  Support suggested doing the following:
{
    "require": {
        "mailgun/mailgun-php": "^3.0",
        "php-http/message": "^1.8",
        "php-http/guzzle6-adapter": "1.1.1",
        "kriswallsmith/buzz": "^1.0",
        "nyholm/psr7": "^1.2"
    }
}

Which I did and ran 
>composer update

But this produces the same exception?

**Comment by progfrosty** [comment]
Same issue for me following docs, and above comments:

Fatal error: Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors
 - Puli Factory is not available
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: .
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: Nyholm\Psr7\Factory\Psr17Factory, Zend\Diactoros\UriFactory, Http\Factory\Diactoros\UriFactory, Http\Factory\Guzzle\UriFactory, Http\Factory\Slim\UriFactory.

**Comment by progfrosty** [comment]
Again for me, nothing works PHP wise.

**Comment by purpletoolz** [comment]
I gave up in the end with Mailgun and went to Sendgrid... Their 'support' just sent me around in circles.

**Comment by progfrosty** [comment]
@purpletoolz - same - Im using curl from within PHP :shrug: only way I could get it working.

**Comment by jorge-brizio** [comment]
Running `composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7` did it for me.

**Comment by DavidGarciaCat** [comment]
The Mailgun Docs using the PHP SDK was not updated for SDK v3.

The Mailgun client is supposed to be instantiated with a named constructor, as mentioned above.

For those getting errors, can you please try with the steps described here?
https://github.com/mailgun/mailgun-php#installation

Cheers,

**Comment by zetagalactic** [comment]
Hello guys, I'm lucky that I have found the solution for this:
on  $mgClient = Mailgun::create('PRIVATE_API_KEY', 'https://API_HOSTNAME');
I have removed the 'https://API_HOSTNAME' and everything worked just fine.

good luck!

**Comment by DavidGarciaCat** [comment]
As stated on the [README's Usage section](https://github.com/mailgun/mailgun-php#usage), the 2nd argument is just required to switch from the US servers to the EU servers

```php
$mg = Mailgun::create('key-example'); // For US servers
$mg = Mailgun::create('key-example', 'https://api.eu.mailgun.net'); // For EU servers
```

If this issue is still a problem, can someone please provide an updated piece of code to reproduce the issue?

Thanks,

**Comment by Nyholm** [comment]
Closing this as it is resolved.

**Comment by paxperscientiam** [comment]
@Nyholm , although docs look good on GH, documentation on website is still wrong. I'm going through the new user walkthrough now and the provided example indicates to instantiate Mailgun/Mailgun with an API key.

![image](https://user-images.githubusercontent.com/7539871/116835217-8d0c5200-ab8f-11eb-886c-d8bd9df56b0a.png)

**Comment by DavidGarciaCat** [comment]
Is that inside your Mailgun Dashboard? I can see updated docs on the documentation page:

https://documentation.mailgun.com/en/latest/api-sending.html#examples

**Comment by paxperscientiam** [comment]
Indeed. Thanks for sharing that link. Unless I'm missing something, that further underscores the problem of example code being wrong.

**Comment by chispitaos** [comment]
Hi Guys, It happens the same to me. I have been using for a long time an old lib. When I upgraded it to v3.5, I get the same error and I solved  this way :

Instead of: 
```
use Mailgun\Mailgun;
$mg = Mailgun::create('key-example');
```

I do: 
`$mg = Mailgun\Mailgun::create('key-example');`

I hope Mailgun team can improve the documentation, mostly for customers that were using old API versions.
A full example for users that upgrade to mailgun 3.5, would be like this:
 
 ```
 $mgClient   =  Mailgun\Mailgun::create('api-key');
  try{

     $attachment = [ 'filePath' => 'file-name-path',
                               // 'fileContent' => base64_encode(file_get_contents( 'file-name-path' )),
                               'filename'    =>'renamed-filename.pdf'];

      $data  = array(
          'subject'  => $subject,  
          'from'  => $from,
          'to'    => implode(",",$to),
          "o:tracking"   => "yes",
          "o:tracking-clicks" => "yes",
          "o:tracking-opens"=> "yes",
          "h:Reply-To"           => $reply_to_mail,
          'html'    => $text,
          'attachment'  => [ $attachment ]
        );  
 
      $response        =  $mgClient->messages()->send($domain, $data);
      $message_id    = $response->getId();
  } catch (Exception $e) {
            echo json_encode($e));
  }

```

**Comment by normanlove222** [comment]
> perhaps would be useful in this instance if the docs reflected the package?

It boggles the mind. I had same error using their own provided code from their sandbox example!! It didnt work, I googled the error and saw this, 2 days later after trying to get support for it. They have the wrong code in TWO different places on their site. :-)

**Comment by ovendoor** [comment]
> Is that inside your Mailgun Dashboard? I can see updated docs on the documentation page:
> 
> https://documentation.mailgun.com/en/latest/api-sending.html#examples

The documents here are still wrong. The code library download referred to in the example code doesn't work this way.

**Comment by binitutor** [comment]
This worked for me and i was able to get emails sent from localhost to my gmail. 
The problem was i was using the test domain provided by mailgun. and that requires recepient email addresses to be verified.
=========> The solution is to make sure you verify the **recipient email** under your domain.
Left Nav > Domains > click on your domain > Scroll below the API and SMTP panel and find the 'recipient authorization' > enter the receiver email and click authorize > check your email for confirmation link from mailgun support > once confirmed, there will be a verified green tag to that email.

=========> Then, you can use the php code below:
$mg = Mailgun::create('xxxapikey'); // For US servers

$domain = "sandboxxxxxxx.mailgun.org"; // domain is the test one provided by mailgun unless you already purchased

$mg->messages()->send($domain , [ 
    'from' => 'SenderEmail@example.com', // can be whatever you want
    'to' => 'recepientEmail@gmail.com', // must be your real, verified email address
    'subject' => 'Example email Subject!', // can be whatever you want
    'text' => 'Example email Body.' // can be whatever you want
]);

// var_dump($mg);
echo 'Success!';
